import dataset_generate
from visual import Input_Target_Pair_Generator
from visual import show_input_target_pair_napari

gen = Input_Target_Pair_Generator(dataset_generate.dataloader_training, rgb=True)
show_input_target_pair_napari(gen)